# Generated by Django 3.0.8 on 2021-11-04 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('select_learn', '0002_auto_20211104_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersentence',
            name='sentence_id',
            field=models.AutoField(db_column='sentence_id', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userword',
            name='sentence_id',
            field=models.ForeignKey(db_column='sentence_id', on_delete=django.db.models.deletion.CASCADE, to='select_learn.UserSentence'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
