# Generated by Django 3.0.8 on 2021-11-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeta',
            old_name='user',
            new_name='user_id',
        ),
    ]
